export const FETCH_CHARACTERS_REQUEST = "FETCH_CHARACTERS_REQUEST";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";
export const FETCH_CHARACTERS_ERROR = "FETCH_CHARACTERS_ERROR";
export const FILTER_BY_SEARCH = "FILTER_BY_SEARCH";
export const FILTER_BY_GENDER = "FILTER_BY_GENDER";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const FILTER_BY_BRANDS = "FILTER_BY_BRANDS";